### ISSUE TITLE
V1.0 Roadmap

### ISSUE THREAD

**Issue by natemoo-re** [natemoo-re/proload#12]
Just sharing some notes for what I'd like to see happen for a v1.0.

- [ ] Default to ESM loading, fallback to `require` (the inverse of the current setup).
- [ ] Move away from `require` hooks. This should improve plugin ergonomics significantly. If a file can't be loaded with `import/require`, we should use `readFile` and the plugin will be responsible for returning a JavaScript representation of the file.
- [ ] Improve API. There are lots of rough edges with the Plugin API that could be smoothed out.
